# Generated by Django 5.2.9 on 2026-06-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('PDF', 'PDF'), ('LINK', 'LINK'), ('VIDEO', 'VIDEO'), ('AI_MENTOR', 'AI_MENTOR')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='course_materials/')),
            ],
        ),
    ]
