# Generated by Django 5.2.9 on 2026-06-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_resumetemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeTemplate',
        ),
    ]
